# Generated by Django 5.2.5 on 2026-03-03 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_feedback', models.TextField(blank=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('APTITUDE', 'Aptitude'), ('CODING', 'Coding'), ('TECHNICAL', 'Technical'), ('HR', 'HR')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_results', to='interview.interviewsession')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'stage_name'), name='unique_stage_result_per_session')],
            },
        ),
    ]
