# Generated by Django 5.2.5 on 2026-03-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_aptitudequestion_aptitudesessionquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium')], max_length=10)),
                ('expected_keywords', models.CharField(blank=True, help_text='Comma separated words used by placeholder evaluator.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CodingSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_mappings', to='interview.codingquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='interview.interviewsession')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CodingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField(blank=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('session_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='interview.codingsessionquestion')),
            ],
            options={
                'ordering': ['session_question__display_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='codingsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_coding_question_per_session'),
        ),
        migrations.AddConstraint(
            model_name='codingsessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'display_order'), name='unique_coding_order_per_session'),
        ),
    ]
