# Generated by Django 5.2.5 on 2026-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_codingquestion_codingsessionquestion_codingresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingresponse',
            name='compile_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codingresponse',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('CPP', 'C++'), ('JS', 'JavaScript')], default='PYTHON', max_length=10),
        ),
        migrations.AddField(
            model_name='codingresponse',
            name='run_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='codingresponse',
            name='run_status',
            field=models.CharField(choices=[('NOT_RUN', 'Not Run'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='NOT_RUN', max_length=12),
        ),
    ]
