# Generated by Django 5.2.5 on 2026-03-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_codingresponse_compile_output_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_clip', models.FileField(blank=True, null=True, upload_to='technical_audio/')),
                ('transcript', models.TextField(blank=True)),
                ('interviewer_notes', models.TextField(blank=True)),
                ('stt_engine', models.CharField(default='browser', max_length=40)),
                ('camera_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_response', to='interview.interviewsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
