# Generated by Django 5.2.5 on 2026-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_technicalresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalresponse',
            name='generated_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='technicalresponse',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='technical_resume/'),
        ),
        migrations.AddField(
            model_name='technicalresponse',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
