# Generated by Django 5.2.12 on 2026-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_technicalresponse_generated_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalresponse',
            name='target_role',
            field=models.CharField(choices=[('AIML', 'AI/ML'), ('WEB_DEV', 'Web Development'), ('PHP', 'PHP Developer'), ('JAVASCRIPT', 'JavaScript Developer'), ('PYTHON', 'Python Developer'), ('GEN_AI', 'Generative AI'), ('JAVA', 'Java Developer'), ('ANGULAR', 'Angular Developer'), ('DOTNET', '.NET Developer')], default='PYTHON', max_length=20),
        ),
    ]
