# Generated by Django 5.2.12 on 2026-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_technicalresponse_target_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalresponse',
            name='target_role',
            field=models.CharField(choices=[('AIML', 'AI/ML'), ('WEB_DEV', 'Web Development'), ('FRONTEND', 'Frontend Developer (HTML/CSS/JS/React)'), ('BACKEND', 'Backend Developer'), ('FULL_STACK', 'Full Stack Developer'), ('MERN_STACK', 'MERN Stack Developer'), ('PHP', 'PHP Developer'), ('JAVASCRIPT', 'JavaScript Developer'), ('PYTHON', 'Python Developer'), ('GEN_AI', 'Generative AI'), ('JAVA', 'Java Developer'), ('ANGULAR', 'Angular Developer'), ('DOTNET', '.NET Developer')], default='PYTHON', max_length=20),
        ),
    ]
