# Generated by Django 5.2.12 on 2026-03-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_alter_technicalresponse_target_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_response', to='interview.interviewsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
