# Generated by Django 5.2.12 on 2026-03-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_hrresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalresponse',
            name='target_role',
            field=models.CharField(choices=[('AIML', 'AIML Engineer'), ('WEB_DEV', 'Web Development'), ('UI_UX', 'UI/UX Designer'), ('FRONTEND', 'Frontend Developer (HTML/CSS/JS/React)'), ('BACKEND', 'Backend Developer'), ('FULL_STACK', 'Full Stack Developer'), ('MERN_STACK', 'MERN Stack Developer'), ('DEVOPS', 'DevOps Engineer'), ('DATA_ANALYST', 'Data Analyst'), ('DATA_SCIENTIST', 'Data Scientist'), ('QA_AUTOMATION', 'QA Automation Engineer'), ('CYBERSECURITY', 'Cybersecurity Analyst'), ('CLOUD_ENGINEER', 'Cloud Engineer'), ('ANDROID', 'Android Developer'), ('IOS', 'iOS Developer'), ('PHP', 'PHP Developer'), ('JAVASCRIPT', 'JavaScript Developer'), ('PYTHON', 'Python Developer'), ('GEN_AI', 'Generative AI'), ('JAVA', 'Java Developer'), ('ANGULAR', 'Angular Developer'), ('DOTNET', '.NET Developer')], default='PYTHON', max_length=20),
        ),
    ]
