# Generated by Django 5.2.5 on 2026-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_alter_technicalresponse_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='test_cases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
