from io import BytesIO

from django.core.files.base import ContentFile
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas


def _draw_header(pdf, width, height, session):
    pdf.setFillColor(colors.HexColor('#1d4ed8'))
    pdf.rect(0, height - 3.3 * cm, width, 3.3 * cm, fill=1, stroke=0)

    pdf.setFillColor(colors.white)
    pdf.setFont('Helvetica-Bold', 18)
    pdf.drawString(1.6 * cm, height - 1.6 * cm, 'AI Interview Practice Tool')

    pdf.setFont('Helvetica', 11)
    pdf.drawString(1.6 * cm, height - 2.3 * cm, f'Final Performance Report • Session #{session.id}')


def _draw_student_box(pdf, start_y, session):
    user = session.user

    pdf.setFillColor(colors.HexColor('#f8fafc'))
    pdf.setStrokeColor(colors.HexColor('#dbe4ef'))
    pdf.roundRect(1.4 * cm, start_y - 4.8 * cm, 18.2 * cm, 4.4 * cm, 8, fill=1, stroke=1)

    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.setFont('Helvetica-Bold', 12)
    pdf.drawString(1.8 * cm, start_y - 1.0 * cm, 'Student Details')

    details = [
        ('Name', f"{user.first_name} {user.last_name}".strip() or user.username),
        ('Username', user.username),
        ('Email', user.email or '-'),
        ('College', getattr(user, 'college', '-') or '-'),
        ('Enrollment No.', getattr(user, 'enrollment_number', '-') or '-'),
        ('Interview Status', session.get_status_display()),
    ]

    y = start_y - 1.8 * cm
    for idx, (label, value) in enumerate(details):
        x = 1.8 * cm if idx % 2 == 0 else 10.6 * cm
        if idx % 2 == 0 and idx > 0:
            y -= 0.85 * cm

        pdf.setFont('Helvetica-Bold', 10)
        pdf.setFillColor(colors.HexColor('#334155'))
        pdf.drawString(x, y, f'{label}:')

        pdf.setFont('Helvetica', 10)
        pdf.setFillColor(colors.HexColor('#0f172a'))
        pdf.drawString(x + 2.6 * cm, y, str(value)[:42])

    return start_y - 5.3 * cm


def _draw_scores_table(pdf, start_y, stage_rows):
    pdf.setFont('Helvetica-Bold', 12)
    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.drawString(1.6 * cm, start_y, 'Stage-wise Scores')

    table_top = start_y - 0.5 * cm
    row_h = 0.9 * cm

    pdf.setFillColor(colors.HexColor('#e2e8f0'))
    pdf.rect(1.4 * cm, table_top - row_h, 18.2 * cm, row_h, fill=1, stroke=0)

    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.setFont('Helvetica-Bold', 10)
    pdf.drawString(1.9 * cm, table_top - 0.58 * cm, 'Stage')
    pdf.drawString(11.0 * cm, table_top - 0.58 * cm, 'Status')
    pdf.drawString(15.0 * cm, table_top - 0.58 * cm, 'Score')

    y = table_top - row_h
    for row in stage_rows:
        y -= row_h
        pdf.setStrokeColor(colors.HexColor('#dbe4ef'))
        pdf.line(1.4 * cm, y, 19.6 * cm, y)

        pdf.setFont('Helvetica', 10)
        pdf.setFillColor(colors.HexColor('#1e293b'))
        pdf.drawString(1.9 * cm, y + 0.3 * cm, row['stage_label'])
        pdf.drawString(11.0 * cm, y + 0.3 * cm, 'Completed' if row['is_completed'] else 'Pending')
        score_text = '-' if row['score'] is None else f"{row['score']}"
        pdf.drawString(15.0 * cm, y + 0.3 * cm, score_text)

    return y - 0.7 * cm


def _draw_summary(pdf, start_y, overall_context):
    pdf.setFillColor(colors.HexColor('#f8fafc'))
    pdf.setStrokeColor(colors.HexColor('#dbe4ef'))
    pdf.roundRect(1.4 * cm, start_y - 4.3 * cm, 18.2 * cm, 3.9 * cm, 8, fill=1, stroke=1)

    pdf.setFillColor(colors.HexColor('#0f172a'))
    pdf.setFont('Helvetica-Bold', 12)
    pdf.drawString(1.8 * cm, start_y - 1.0 * cm, 'Overall Summary')

    summary_lines = [
        f"Overall Score: {overall_context['overall_score']} / 100",
        f"Grade: {overall_context['overall_grade']}  |  Readiness: {overall_context['readiness']}",
        f"Strengths: {', '.join(overall_context['strengths']) if overall_context['strengths'] else '-'}",
        f"Improvements: {', '.join(overall_context['improvements']) if overall_context['improvements'] else '-'}",
    ]

    y = start_y - 1.8 * cm
    pdf.setFont('Helvetica', 10)
    pdf.setFillColor(colors.HexColor('#334155'))
    for line in summary_lines:
        pdf.drawString(1.8 * cm, y, line)
        y -= 0.7 * cm


def build_session_report_pdf(session, overall_context):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    _draw_header(pdf, width, height, session)

    cursor_y = height - 3.9 * cm
    cursor_y = _draw_student_box(pdf, cursor_y, session)
    cursor_y = _draw_scores_table(pdf, cursor_y, overall_context['stage_rows'])
    _draw_summary(pdf, cursor_y, overall_context)

    pdf.setFont('Helvetica', 8)
    pdf.setFillColor(colors.HexColor('#64748b'))
    pdf.drawString(1.6 * cm, 1.3 * cm, 'Generated by AI Interview Practice Tool')

    pdf.showPage()
    pdf.save()

    buffer.seek(0)
    return ContentFile(buffer.read())
